Repository mansi2024/ScoreDisplayer, pull requests merged in 2021-10, with the labels that each got.

#1 Updated README.md
  README.md
Labels: hacktoberfest

#3 Submit works
  index.html
  project.js
Labels: hacktoberfest

#4 Revert "Submit works"
  index.html
  project.js
Labels: hactoberfest-accepted

#5 Added logo on tab
  icon.ico
  index.html
Labels: hactoberfest-accepted

#6 Update index.html
  index.html
Labels: hacktoberfest-accepted
